CREATE TABLE IF NOT EXISTS concerts (
  id bigint,
  type text,
  uri text,
  displayName text,
  start.time text,
  start.date text,
  start.datetime text,
  location.city text,
  location.lng double precision,
  location.lat double precision,
  venue.id bigint,
  venue.displayName text,
  venue.uri text,
  venue.lng double precision,
  venue.lat double precision,
  venue.metroArea.uri text,
  venue.metroArea.displayName text,
  venue.metroArea.country.displayName text,
  venue.metroArea.id bigint,
  venue.metroArea.state.displayName text,
  status text,
  popularity double precision
);
